# Generated by Django 4.1.2 on 2022-10-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0005_lyric_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='song_id',
            field=models.CharField(max_length=400),
        ),
    ]
