# Generated by Django 4.1.2 on 2022-10-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0007_song_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='likes',
        ),
    ]
